[phases.setup]
nixPkgs = ["cairo", "pango", "libpng", "libjpeg", "giflib", "librsvg", "pkg-config", "fontconfig", "freetype", "dejavu_fonts", "liberation_ttf", "noto-fonts"]

[phases.install]
cmds = ["npm install", "fc-cache -f -v || true"]

[start]
cmd = "node index.js"
